export const names = [
    "Dale Cooper",
    "Laura Palmer",
    "Leland Palmer",
    "Sarah Palmer",
    "Audrey Horne",
    "Benjamin Horne",
    "Jerry Horne",
    "Bobby Briggs",
    "Garland Briggs",
    "Betty Briggs",
    "Shelly Johnson",
    "Leo Johnson",
    "Norma Jennings",
    "Hank Jennings",
    "Ed Hurley",
    "Nadine Hurley",
    "James Hurley",
    "Donna Hayward",
    "Will Hayward",
    "Eileen Hayward",
    "Harold Smith",
    "Maddy Ferguson",
    "Josie Packard",
    "Andrew Packard",
    "Pete Martell",
    "Catherine Martell",
    "Thomas Eckhardt",
    "The Giant",
    "The Man from Another Place",
    "BOB",
    "MIKE",
    "Phillip Gerard",
    "The Arm",
    "The Jumping Man",
    "The Fireman",
    "Senorita Dido",
    "Margaret Lanterman",
    "Deputy Hawk",
    "Harry Truman",
    "Frank Truman",
    "Lucy Moran",
    "Andy Brennan",
    "Dick Tremayne",
    "Albert Rosenfield",
    "Gordon Cole",
    "Denise Bryson",
    "Diane Evans",
    "Phillip Jeffries",
    "Windom Earle",
    "Annie Blackburn",
    "Jacques Renault",
    "Jean-Michel Renault",
    "Bernard Renault",
    "Blackie O'Reilly",
    "Emory Battis",
    "Ernie Niles",
    "Johnny Horne",
    "Sylvia Horne",
    "Lawrence Jacoby",
    "Teresa Banks",
    "Chet Desmond",
    "Sam Stanley",
    "Carl Rodd",
    "Mrs. Tremond",
    "Pierre Tremond",
    "The Woodsmen",
    "The Experiment",
    "Naido",
    "Freddie Sykes",
    "Red",
    "Richard Horne",
    "Miriam Sullivan",
    "Steven Burnett",
    "Gersten Hayward",
    "Becky Burnett",
    "Wally Brando",
    "Bill Hastings",
    "Phyllis Hastings",
    "Detective Macklay",
    "Constance Talbot",
    "Tammy Preston",
    "Janey-E Jones",
    "Sonny Jim Jones",
    "Dougie Jones",
    "Anthony Sinclair",
    "Duncan Todd",
    "Roger Hardy",
    "Buella",
    "Chantal Hutchens",
    "Hutch",
    "Ike Stadtler",
    "Jack Wheeler",
    "Jade",
    "Lorraine",
    "Renzo",
    "Rodney Mitchum",
    "Bradley Mitchum",
    "Candy",
];
